### ISSUE TITLE
TODO & Why removed transparent versions?

### ISSUE THREAD

**Issue by varlesh** [PapirusDevelopmentTeam/arc-kde#59]
- [x] Delete transparent versions
- [x] Update MAKEFILE
- [x] Update installation scripts
- [x] Add & Fix Arrow on Arc Darker Kvantum Theme
- [x] Redesign & Check Yakuake Theme
- [x] ~~Remove Firefox Patch (not supported anymore)~~ & Telegram (not needed)

**Comment by francoism90** [comment]
Is it possible to add some styles to SDDM?

**Comment by varlesh** [comment]
> Is it possible to add some styles to SDDM?

Maybe, but based on other theme ;) I don't know QML

**Comment by francoism90** [comment]
Thanks for your reply, not a deal breaker, but just would like to know if it would be possible. :)

**Comment by nerdius** [comment]
> - [x] Delete transparent versions

This broke theming on my system today. May I know the reason?

**Comment by varlesh** [comment]
@giogziro95 Don't worry, theme archived. You can download previous version on 20170908 release:
https://github.com/PapirusDevelopmentTeam/arc-kde/releases/tag/20170908

> May I know the reason?

Yes. Because transparency not support for GTK-apps on KDE, it's looking not good and different - qt use transparency, gtk not.

But see, now Qt and GTK apps looks similar:
![image](https://user-images.githubusercontent.com/8083855/30250217-806f1a66-965b-11e7-9f02-53f3d7c2e472.png)

**Comment by nerdius** [comment]
@varlesh Understandable, but it'd be great if there was an option for transparency (for Qt-based applications) if the user wants to have it.

So, is the latest commit to the older version e06279795dc92c02d8431c263d93d798c9acedd5? I've created a [fork](https://github.com/giogziro95/arc-kde) to make the older version easily installable.

**Comment by varlesh** [comment]
@giogziro95 Yes, you right.

**Comment by ArchangeGabriel** [comment]
The latest version with transparency is also available at the 20170908 release as stated above. ;)

@varlesh Do you plan on tagging another release with all the new changes in?

**Comment by ArchangeGabriel** [comment]
Thank you for the new release. Regarding transparency, something I don’t understand: there is an arc-transparent version of the GTK theme, right? So this would be great if used together with an arc-kde transparent version.

**Comment by varlesh** [comment]
@ArchangeGabriel Yes, Arc GTK have transparency, but on KDE used solid theme only

**Comment by varlesh** [comment]
Install nautilus or other GTK 3 run and see:
![image](https://user-images.githubusercontent.com/8083855/30320302-49233b28-97c3-11e7-8723-c657d1ebac50.png)

**Comment by varlesh** [comment]
Yes, Nautilus not needed on KDE... but other apps like as Firefox, Chromium, inkscape, Gimp - this app not have analog on Qt.

**Comment by varlesh** [comment]
If KDE devs add support for transparency on GTK 3 apps - i'm add Transparent version too. But now discontinued!

**Comment by ArchangeGabriel** [comment]
OK I see, Kwin or something in KDE doesn’t support GTK3 themes with transparency. Then I totally agree with you!

Thanks for this updated theme btw.
